### ISSUE TITLE
ERROR: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by nemobis** [enricobacis/wos#15] opened 2017-10-06 19:56 UTC
I'm consistently getting ascii codec errors for a series of DOIs, queried by `wos --sid $sid query "DO=$doi"`.

DOI | Error
-|-
10.4049/jimmunol.1401025 | ERROR: 'ascii' codec can't encode character u'\ubc30' in position 12084: ordinal not in range(128)
10.1111/j.1745-6584.2000.tb00251.x | ERROR: 'ascii' codec can't encode character u'\u5f20' in position 9279: ordinal not in range(128)
10.1143/JPSJ.74.483 | ERROR: 'ascii' codec can't encode characters in position 7325-7326: ordinal not in range(128)
10.1016/S0378-1119(98)00302-3 | ERROR: 'ascii' codec can't encode characters in position 9692-9696: ordinal not in range(128)
10.1073/pnas.1111282109 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 17585: ordinal not in range(128)
10.1016/0889-5406(87)90232-0 | ERROR: 'ascii' codec can't encode character u'\u56de' in position 5300: ordinal not in range(128)
10.1016/S0024-3205(02)01962-8 | ERROR: 'ascii' codec can't encode characters in position 10298-10302: ordinal not in range(128)
10.1093/cvr/cvp066 | ERROR: 'ascii' codec can't encode character u'\u738b' in position 10877: ordinal not in range(128)
10.1038/nature06815 | ERROR: 'ascii' codec can't encode character u'\ufffd' in position 36527: ordinal not in range(128)
10.1016/S1286-4579(02)01598-8 | ERROR: 'ascii' codec can't encode characters in position 10997-10999: ordinal not in range(128)
10.1007/s11307-011-0497-z | ERROR: 'ascii' codec can't encode character u'\uae40' in position 15123: ordinal not in range(128)
10.1080/00018732.2015.1114338 | ERROR: 'ascii' codec can't encode character u'\u8463' in position 18994: ordinal not in range(128)
10.1016/S0012-8252(00)00037-4 | ERROR: 'ascii' codec can't encode character u'\u8c2d' in position 7927: ordinal not in range(128)
10.1039/C4CC07220K | ERROR: 'ascii' codec can't encode character u'\u9ec4' in position 13295: ordinal not in range(128)
10.1093/eurheartj/ehr218 | ERROR: 'ascii' codec can't encode character u'\u5218' in position 29671: ordinal not in range(128)
10.1039/C5CC01090J | ERROR: 'ascii' codec can't encode character u'\u8d56' in position 14106: ordinal not in range(128)
10.1126/science.287.5457.1433 | ERROR: 'ascii' codec can't encode character u'\u51af' in position 6062: ordinal not in range(128)
10.1016/j.jphotobiol.2009.04.006 | ERROR: 'ascii' codec can't encode character u'\u9648' in position 12661: ordinal not in range(128)
10.1002/(SICI)1097-4644(20000301)76:3<499::AID-JCB16>3.0.CO;2-4 | ERROR: 'ascii' codec can't encode characters in position 9327-9331: ordinal not in range(128)
10.3987/COM-10-S(E)27 | ERROR: 'ascii' codec can't encode characters in position 9334-9335: ordinal not in range(128)
10.1146/annurev.immunol.21.120601.141007 | ERROR: 'ascii' codec can't encode character u'\u51af' in position 11023: ordinal not in range(128)
10.1111/1467-985x.00154 | ERROR: 'ascii' codec can't encode character u'\u5d07' in position 7628: ordinal not in range(128)
10.1038/nrc2067 | ERROR: 'ascii' codec can't encode characters in position 7246-7247: ordinal not in range(128)
10.1093/jb/mvg053 | ERROR: 'ascii' codec can't encode characters in position 10663-10664: ordinal not in range(128)
10.1109/FOCS.2008.34 | ERROR: 'ascii' codec can't encode characters in position 12869-12870: ordinal not in range(128)
10.1063/1.1480877 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7361: ordinal not in range(128)
10.1016/j.molbrainres.2003.09.014 | ERROR: 'ascii' codec can't encode character u'\u8c2d' in position 9257: ordinal not in range(128)
10.1039/AN9952000917 | ERROR: 'ascii' codec can't encode character u'\u5f20' in position 8521: ordinal not in range(128)
10.1016/j.foreco.2005.10.019 | ERROR: 'ascii' codec can't encode character u'\ufffd' in position 8014: ordinal not in range(128)
10.1093/eurheartj/ehq406 | ERROR: 'ascii' codec can't encode character u'\u5218' in position 22630: ordinal not in range(128)
10.1109/TPDS.2011.159 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 13869: ordinal not in range(128)
10.1002/jcb.1110 | ERROR: 'ascii' codec can't encode characters in position 10233-10237: ordinal not in range(128)
10.1007/s004420050208 | ERROR: 'ascii' codec can't encode character u'\x85' in position 6038: ordinal not in range(128)
10.1103/PhysRevB.86.081301 | ERROR: 'ascii' codec can't encode character u'\u5218' in position 15746: ordinal not in range(128)
10.1016/j.scitotenv.2005.09.030 | ERROR: 'ascii' codec can't encode character u'\u738b' in position 9919: ordinal not in range(128)
10.2174/1381612821666151008124036 | ERROR: 'ascii' codec can't encode character u'\x9b' in position 16161: ordinal not in range(128)
10.1002/jcb.1217 | ERROR: 'ascii' codec can't encode characters in position 9816-9820: ordinal not in range(128)
10.1007/s11629-011-2180-x | ERROR: 'ascii' codec can't encode character u'\u674e' in position 9436: ordinal not in range(128)
10.1002/14651858.cd004485.pub3 | ERROR: 'ascii' codec can't encode character u'\u6bb5' in position 9384: ordinal not in range(128)
10.1103/PhysRevLett.100.206803 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 11885: ordinal not in range(128)
10.1038/nri2017 | ERROR: 'ascii' codec can't encode characters in position 18883-18884: ordinal not in range(128)
10.1126/science.1081294 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7734: ordinal not in range(128)
10.1038/nrgastro.2011.196 | ERROR: 'ascii' codec can't encode character u'\u6797' in position 11173: ordinal not in range(128)
10.1038/nature01210 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7471: ordinal not in range(128)
10.1016/j.gene.2005.08.021 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 12664: ordinal not in range(128)
10.1006/bbrc.1994.2693 | ERROR: 'ascii' codec can't encode characters in position 5995-5999: ordinal not in range(128)
10.1080/10408430208500497 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7802: ordinal not in range(128)
10.1016/S0140-6736(03)14230-4 | ERROR: 'ascii' codec can't encode characters in position 14211-14212: ordinal not in range(128)
10.1039/b201447e | ERROR: 'ascii' codec can't encode character u'\u738b' in position 7271: ordinal not in range(128)
10.1136/hrt.2007.125401 | ERROR: 'ascii' codec can't encode character u'\u5e94' in position 9807: ordinal not in range(128)
10.1016/j.jconrel.2011.07.010 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 14238: ordinal not in range(128)
10.1002/1097-4644(20000915)78:4<558::AID-JCB5>3.0.CO;2-I | ERROR: 'ascii' codec can't encode characters in position 12130-12134: ordinal not in range(128)
10.1016/S0031-0182(01)00361-3 | ERROR: 'ascii' codec can't encode characters in position 12127-12131: ordinal not in range(128)
10.1245/s10434-010-1188-8 | ERROR: 'ascii' codec can't encode character u'\u4e01' in position 18954: ordinal not in range(128)
10.1111/dme.12314 | ERROR: 'ascii' codec can't encode character u'\x9b' in position 12831: ordinal not in range(128)
10.1039/B401321M | ERROR: 'ascii' codec can't encode character u'\u5f20' in position 5572: ordinal not in range(128)
10.1038/nnano.2010.89 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7370: ordinal not in range(128)
10.1007/s000240050163 | ERROR: 'ascii' codec can't encode characters in position 7449-7450: ordinal not in range(128)
10.1016/S0378-1119(99)00251-6 | ERROR: 'ascii' codec can't encode characters in position 10518-10522: ordinal not in range(128)
10.1016/j.measurement.2011.11.001 | ERROR: 'ascii' codec can't encode character u'\u80e1' in position 9023: ordinal not in range(128)
10.1681/ASN.2005080866 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 14183: ordinal not in range(128)
10.1080/01972243.2012.632264 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 8248: ordinal not in range(128)
10.1159/000134638 | ERROR: 'ascii' codec can't encode characters in position 5246-5250: ordinal not in range(128)
10.1016/S0040-4039(00)94379-X | ERROR: 'ascii' codec can't encode characters in position 4149-4150: ordinal not in range(128)
10.1016/S0883-2927(02)00018-5 | ERROR: 'ascii' codec can't encode character u'\u5f20' in position 9149: ordinal not in range(128)
10.1146/annurev.pathol.1.110304.100224 | ERROR: 'ascii' codec can't encode characters in position 8970-8971: ordinal not in range(128)
10.1016/j.chemosphere.2011.05.054 | ERROR: 'ascii' codec can't encode character u'\u9a86' in position 8665: ordinal not in range(128)
10.1016/j.electacta.2011.06.111 | ERROR: 'ascii' codec can't encode character u'\u7530' in position 13702: ordinal not in range(128)
10.1038/nm0798-839 | ERROR: 'ascii' codec can't encode characters in position 11659-11660: ordinal not in range(128)
10.1016/0888-7543(92)90157-N | ERROR: 'ascii' codec can't encode character u'\u90d1' in position 6233: ordinal not in range(128)
10.1038/nphoton.2007.75 | ERROR: 'ascii' codec can't encode character u'\u5f20' in position 9986: ordinal not in range(128)
10.1002/14651858.CD004485.pub3 | ERROR: 'ascii' codec can't encode character u'\u6bb5' in position 9384: ordinal not in range(128)
10.1016/S0041-0101(03)00129-6 | ERROR: 'ascii' codec can't encode characters in position 2866-2867: ordinal not in range(128)
10.1002/jcb.10041 | ERROR: 'ascii' codec can't encode characters in position 10682-10686: ordinal not in range(128)
10.1126/science.1058782 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 6560: ordinal not in range(128)
10.1038/nnano.2007.300 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7136: ordinal not in range(128)
10.1093/aob/mcq177 | ERROR: 'ascii' codec can't encode character u'\u4f59' in position 12867: ordinal not in range(128)
10.1159/000015489 | ERROR: 'ascii' codec can't encode characters in position 8084-8088: ordinal not in range(128)
10.1111/1467-9280.00325 | ERROR: 'ascii' codec can't encode character u'\u5d07' in position 6784: ordinal not in range(128)
10.1109/TPS.2014.2299277 | ERROR: 'ascii' codec can't encode character u'\u5f6d' in position 21134: ordinal not in range(128)
10.1046/j.1439-0485.2000.00689.x | ERROR: 'ascii' codec can't encode characters in position 7088-7089: ordinal not in range(128)
10.1016/S0926-6410(02)00302-6 | ERROR: 'ascii' codec can't encode characters in position 8901-8902: ordinal not in range(128)
10.1038/35057062 | ERROR: 'ascii' codec can't encode character u'\u90d1' in position 118579: ordinal not in range(128)
10.1063/1.126107 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 6342: ordinal not in range(128)
10.1245/s10434-010-1082-4 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 23545: ordinal not in range(128)
10.1016/S0378-1119(97)00644-6 | ERROR: 'ascii' codec can't encode characters in position 8937-8941: ordinal not in range(128)
10.1351/pac199163030419 | ERROR: 'ascii' codec can't encode characters in position 6347-6348: ordinal not in range(128)
10.1016/j.jconrel.2008.07.013 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 18252: ordinal not in range(128)
10.1063/1.118061 | ERROR: 'ascii' codec can't encode character u'\u9a6c' in position 7498: ordinal not in range(128)
10.1093/eurheartj/ehr158 | ERROR: 'ascii' codec can't encode character u'\u5218' in position 12890: ordinal not in range(128)
10.1002/ep.10606 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 12919: ordinal not in range(128)
10.1038/sj.onc.1206269 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 11152: ordinal not in range(128)
10.1016/j.biocel.2007.06.004 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 8085: ordinal not in range(128)
10.1038/nature04796 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 9086: ordinal not in range(128)
10.3109/10425170009033988 | ERROR: 'ascii' codec can't encode character u'\u90d1' in position 11666: ordinal not in range(128)
10.1016/j.annemergmed.2010.05.037 | ERROR: 'ascii' codec can't encode characters in position 4137-4138: ordinal not in range(128)
10.1016/j.progpolymsci.2011.06.004 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 11752: ordinal not in range(128)
10.1039/C3CS60323G | ERROR: 'ascii' codec can't encode character u'\u6c88' in position 15235: ordinal not in range(128)
10.1029/2008JB005814 | ERROR: 'ascii' codec can't encode characters in position 10713-10717: ordinal not in range(128)
10.1126/science.1091022 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7525: ordinal not in range(128)
10.1016/S0006-291X(02)02605-0 | ERROR: 'ascii' codec can't encode character u'\u8449' in position 10295: ordinal not in range(128)
10.1093/eurheartj/ehq278 | ERROR: 'ascii' codec can't encode character u'\u5218' in position 13664: ordinal not in range(128)
10.1126/science.1122797 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 9048: ordinal not in range(128)
10.1016/S0022-328X(98)01055-9 | ERROR: 'ascii' codec can't encode characters in position 7248-7249: ordinal not in range(128)
10.1023/B:SCAM.0000007122.03392.4b | ERROR: 'ascii' codec can't encode characters in position 9194-9198: ordinal not in range(128)
10.1002/1097-4644(20010301)80:3<293::AID-JCB10>3.0.CO;2-U | ERROR: 'ascii' codec can't encode characters in position 10838-10842: ordinal not in range(128)
10.1007/s10458-005-2631-2 | ERROR: 'ascii' codec can't encode characters in position 7598-7599: ordinal not in range(128)
10.1126/science.1090899 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 8180: ordinal not in range(128)
10.1016/S0048-9697(99)00524-0 | ERROR: 'ascii' codec can't encode character u'\u5f20' in position 6465: ordinal not in range(128)
10.1557/JMR.2001.0457 | ERROR: 'ascii' codec can't encode character u'\u6768' in position 9771: ordinal not in range(128)
10.1016/j.jconrel.2011.06.043 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 18877: ordinal not in range(128)
10.1016/j.jclepro.2012.11.020 | ERROR: 'ascii' codec can't encode character u'\u4e8e' in position 11942: ordinal not in range(128)
10.1038/sj.mp.4001939 | ERROR: 'ascii' codec can't encode character u'\u8521' in position 10294: ordinal not in range(128)
10.1016/j.ces.2011.10.068 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 12067: ordinal not in range(128)
10.1016/0167-4781(95)00224-3 | ERROR: 'ascii' codec can't encode characters in position 8055-8059: ordinal not in range(128)
10.1107/s0907444900014062 | ERROR: 'ascii' codec can't encode characters in position 7934-7935: ordinal not in range(128)
10.1128/MCB.01993-07 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 12228: ordinal not in range(128)
10.1111/j.1540-6210.2011.02228.x | ERROR: 'ascii' codec can't encode character u'\u674e' in position 8659: ordinal not in range(128)
10.1016/j.materresbull.2009.03.015 | ERROR: 'ascii' codec can't encode character u'\xb7' in position 10921: ordinal not in range(128)
10.1246/cl.1986.357 | ERROR: 'ascii' codec can't encode characters in position 4217-4218: ordinal not in range(128)
10.1002/(SICI)1097-4644(20000201)76:2<231::AID-JCB7>3.0.CO;2-X | ERROR: 'ascii' codec can't encode character u'\uae40' in position 11428: ordinal not in range(128)
10.1007/s00395-011-0235-3 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 15436: ordinal not in range(128)
10.1002/(SICI)1097-4644(19990401)73:1<31::AID-JCB4>3.0.CO;2-X | ERROR: 'ascii' codec can't encode characters in position 7818-7822: ordinal not in range(128)
10.1016/j.electacta.2007.06.021 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7670: ordinal not in range(128)
10.1111/j.1745-6584.1988.tb00397.x | ERROR: 'ascii' codec can't encode character u'\u5f20' in position 4738: ordinal not in range(128)
10.1006/jmcc.1999.0937 | ERROR: 'ascii' codec can't encode character u'\u8449' in position 9961: ordinal not in range(128)
10.1103/PhysRevLett.93.196805 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7017: ordinal not in range(128)
10.1006/geno.1997.4990 | ERROR: 'ascii' codec can't encode characters in position 6522-6526: ordinal not in range(128)
10.1006/geno.1997.5134 | ERROR: 'ascii' codec can't encode characters in position 7297-7301: ordinal not in range(128)
10.1016/j.bmc.2012.05.049 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 21112: ordinal not in range(128)
10.1002/btpr.727 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 9516: ordinal not in range(128)
10.1017/S0029665108007088 | ERROR: 'ascii' codec can't encode character u'\u8c2d' in position 9521: ordinal not in range(128)
10.1126/science.1135901 | ERROR: 'ascii' codec can't encode characters in position 20214-20215: ordinal not in range(128)
10.1002/jmv.20177 | ERROR: 'ascii' codec can't encode characters in position 11386-11394: ordinal not in range(128)
10.1016/S1369-7021(06)71653-4 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 6517: ordinal not in range(128)
10.1038/nature08610 | ERROR: 'ascii' codec can't encode character u'\u738b' in position 17636: ordinal not in range(128)
10.1126/science.1152793 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 12613: ordinal not in range(128)
10.1016/j.chemosphere.2007.03.028 | ERROR: 'ascii' codec can't encode characters in position 8217-8218: ordinal not in range(128)
10.1046/j.1440-1819.2003.01110.x | ERROR: 'ascii' codec can't encode characters in position 3729-3730: ordinal not in range(128)
10.1038/nature03001 | ERROR: 'ascii' codec can't encode character u'\u90d1' in position 8473: ordinal not in range(128)
10.1063/1.122477 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7181: ordinal not in range(128)
10.1006/bbrc.1999.0178 | ERROR: 'ascii' codec can't encode characters in position 9508-9512: ordinal not in range(128)
10.1093/bioinformatics/19.2.185 | ERROR: 'ascii' codec can't encode character u'\u5b89' in position 10983: ordinal not in range(128)
10.1016/j.jconrel.2008.07.020 | ERROR: 'ascii' codec can't encode character u'\uae40' in position 19639: ordinal not in range(128)
10.1111/j.1521-0391.2013.00336.x | ERROR: 'ascii' codec can't encode character u'\u2010' in position 7455: ordinal not in range(128)
10.1002/ldr.563 | ERROR: 'ascii' codec can't encode characters in position 4610-4611: ordinal not in range(128)
10.1088/0953-8984/23/10/105603 | ERROR: 'ascii' codec can't encode character u'\u77f3' in position 7507: ordinal not in range(128)
10.1046/j.1365-2125.2003.01895.x | ERROR: 'ascii' codec can't encode characters in position 4356-4357: ordinal not in range(128)
10.1038/nature01797 | ERROR: 'ascii' codec can't encode character u'\u674e' in position 7869: ordinal not in range(128)
10.1111/j.1741-2358.2007.00197.x | ERROR: 'ascii' codec can't encode character u'\u6bb5' in position 9804: ordinal not in range(128)
10.3758/BF03206553 | ERROR: 'ascii' codec can't encode character u'\u5218' in position 7406: ordinal not in range(128)
10.1002/(SICI)1097-4644(19990201)72:2<279::AID-JCB12>3.0.CO;2-7 | ERROR: 'ascii' codec can't encode characters in position 8947-8951: ordinal not in range(128)

**Comment by enricobacis** [comment] 2017-11-15 11:45
Hi, are you using python2 or python3? Also, which version of wos are you using? Because this should have been fixed since 0.1.9, in fact I can't reproduce the error.

**Comment by nemobis** [comment] 2017-11-15 11:56
Thanks for testing. I think I have both python2 and python3 installed and I installed wos with pip, but I'll check again at home.

**Comment by enricobacis** [comment] 2017-11-15 12:00
Try to do

pip install --upgrade wos

**Comment by enricobacis** [comment] 2017-12-11 18:50
I'm closing this to cleanup. Feel free to reopen if this issue is still affecting you.

**Closed as completed by enricobacis** 2017-12-11 18:50 UTC
