### ISSUE TITLE
Invalid record output 

### ISSUE THREAD

**Issue by geekdinazor** [enricobacis/wos#29] opened 2018-10-23 07:10 UTC
### Prerequisites

Make sure these boxes are checked before filling an issue

* [x] This issue is not the `No matches returned for Username or IP` 
  connection problem detailed [here](https://github.com/enricobacis/wos#faq-i-cannot-connect-)
* [X] I can reproduce the problem
* [X] I am running the latest version

### Version
Version: 0.1.15

### Description

Some records parsed incorrectly in wos package. Output was: 
```
Authenticated (SID: XXX)
<?xml version="1.0" ?>
<records></records>
</records>
```
but when I try it with R package (wosr) seems parsed correctly.

### Steps to Reproduce

1. `wos --user PremiumUser --password Password query 'UT=000368341300002' -c1`
or python equivalent. I realize that 59 more accession numbers fit that issue. If you want, I can send them, too.

**Expected behavior:**  Record should parsed correctly
**Actual behavior:** Incorrect output (see upper)

**Comment by enricobacis** [comment] 2018-10-23 13:42
Hi,

I tried your search query here

https://apps.webofknowledge.com/WOS_AdvancedSearch_input.do?product=WOS&search_mode=AdvancedSearch&replaceSetId=&goToPageLoc=SearchHistoryTableBanner

and it cannot find any result, I'm not sure why another package is providing answers. Could you also try to perform an online search and check the results?

**Comment by geekdinazor** [comment] 2018-10-23 15:11
Yes, I've checked and get result. Sorry I've fixed it.
![Result](https://i.imgur.com/y2p45fE.png)

**Comment by enricobacis** [comment] 2018-10-23 15:20
I can't open the link: 403 Forbidden

**Comment by enricobacis** [comment] 2018-10-24 09:24
I'm sorry but I can't still find it, so I can't reproduce it and debug it. It might be a problem with wos itself, you might want to check with them directly.

**Comment by enricobacis** [comment] 2019-04-16 08:24
I'm closing this for now. Feel free to reopen it if you want to provide more details.

**Closed as completed by enricobacis** 2019-04-16 08:24 UTC
